/**
 * Connectivity checks for every external service lovorld depends on.
 * Run with `npm run check` after editing .env.local — each check makes the
 * smallest possible call against the real service and reports OK / a precise
 * failure reason. The intent is "tell me which key is wrong" rather than
 * "the dev server crashes 30 seconds in".
 */
import { config as loadEnv } from "dotenv";

loadEnv({ path: ".env.local", override: true });
loadEnv({ path: ".env", override: false });

import { HeadBucketCommand, S3Client } from "@aws-sdk/client-s3";
import postgres from "postgres";

type Result = { name: string; status: "ok" | "fail" | "skip"; detail?: string };

const results: Result[] = [];

async function runCheck(name: string, fn: () => Promise<string | void>): Promise<void> {
  process.stdout.write(`• ${name.padEnd(28)} `);
  try {
    const detail = await fn();
    results.push({ name, status: "ok", detail: detail ?? undefined });
    console.log(`\x1b[32mOK\x1b[0m${detail ? ` — ${detail}` : ""}`);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (message.startsWith("SKIP:")) {
      results.push({ name, status: "skip", detail: message.slice(5).trim() });
      console.log(`\x1b[33mSKIP\x1b[0m — ${message.slice(5).trim()}`);
    } else {
      results.push({ name, status: "fail", detail: message });
      console.log(`\x1b[31mFAIL\x1b[0m\n    ${message}`);
    }
  }
}

function requireEnv(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`SKIP: ${name} is not set in .env.local`);
  if (v === "demo" || v.startsWith("demo:") || v.includes("placeholder")) {
    throw new Error(`SKIP: ${name} is still the demo placeholder`);
  }
  return v;
}

async function checkPostgres() {
  const url = requireEnv("DATABASE_URL");
  const client = postgres(url, {
    max: 1,
    idle_timeout: 5,
    connect_timeout: 10,
  });
  try {
    const versionRows = await client<{ server_version: string }[]>`
      SELECT current_setting('server_version') AS server_version
    `;
    const extRows = await client<{ extname: string }[]>`
      SELECT extname FROM pg_extension WHERE extname = 'vector'
    `;
    if (extRows.length === 0) {
      throw new Error(
        `connected (Postgres ${versionRows[0].server_version}) but pgvector is NOT installed. Run: CREATE EXTENSION vector;`,
      );
    }
    return `Postgres ${versionRows[0].server_version}, pgvector installed`;
  } finally {
    await client.end({ timeout: 5 });
  }
}

async function checkStorage() {
  if (process.env.LOVORLD_LOCAL_STORAGE === "1") {
    return "using local filesystem (./uploads) — cloud storage bypassed";
  }
  if (process.env.BLOB_READ_WRITE_TOKEN) {
    if (!process.env.BLOB_PUBLIC_URL) {
      throw new Error(
        "BLOB_READ_WRITE_TOKEN is set but BLOB_PUBLIC_URL is missing. Set BLOB_PUBLIC_URL to your store's public CDN host (https://<store-id>.public.blob.vercel-storage.com).",
      );
    }
    return `vercel-blob ready (token present, public URL=${process.env.BLOB_PUBLIC_URL})`;
  }
  const accountId = requireEnv("R2_ACCOUNT_ID");
  const accessKeyId = requireEnv("R2_ACCESS_KEY_ID");
  const secretAccessKey = requireEnv("R2_SECRET_ACCESS_KEY");
  const bucket = process.env.R2_BUCKET ?? "lovorld-images";

  const client = new S3Client({
    region: "auto",
    endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
    credentials: { accessKeyId, secretAccessKey },
  });

  await client.send(new HeadBucketCommand({ Bucket: bucket }));
  return `bucket "${bucket}" reachable`;
}

// 16×16 solid red PNG, base64. Some vision providers (DashScope Qwen-VL)
// reject images smaller than 10px per side, so we stay well above that.
// Generated by src/scripts/make-test-png.ts — verified to decode cleanly.
const RED_16PX_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAF0lEQVR4nGP4z8BAEiJN9aiGUQ1DSgMAkPn/Afnh+ngAAAAASUVORK5CYII=";

async function checkVision() {
  const baseUrl = (
    process.env.VISION_BASE_URL ?? "https://dashscope.aliyuncs.com/compatible-mode/v1"
  ).replace(/\/$/, "");
  const apiKey = requireEnv("VISION_API_KEY");
  const model = process.env.VISION_MODEL ?? "qwen-vl-max";

  const res = await fetch(`${baseUrl}/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      messages: [
        {
          role: "user",
          content: [
            {
              type: "image_url",
              image_url: {
                url: `data:image/png;base64,${RED_16PX_PNG_BASE64}`,
              },
            },
            {
              type: "text",
              text: 'Reply with this JSON only: {"ok":true}',
            },
          ],
        },
      ],
      max_tokens: 50,
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`HTTP ${res.status} ${res.statusText}: ${body.slice(0, 200)}`);
  }
  const json = (await res.json()) as {
    choices?: { message?: { content?: string } }[];
  };
  const content = json.choices?.[0]?.message?.content;
  if (!content) throw new Error("vision endpoint returned no content");
  return `${model} → image input accepted`;
}

async function checkEmbedding() {
  const baseUrl = (
    process.env.EMBEDDING_BASE_URL ?? "https://dashscope.aliyuncs.com/compatible-mode/v1"
  ).replace(/\/$/, "");
  const apiKey = requireEnv("EMBEDDING_API_KEY");
  const model = process.env.EMBEDDING_MODEL ?? "text-embedding-v3";

  const res = await fetch(`${baseUrl}/embeddings`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model,
      input: "lovorld check",
      dimensions: 1024,
      encoding_format: "float",
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`HTTP ${res.status} ${res.statusText}: ${body.slice(0, 200)}`);
  }
  const json = (await res.json()) as { data?: { embedding?: number[] }[] };
  const dims = json.data?.[0]?.embedding?.length ?? 0;
  if (dims !== 1024) {
    throw new Error(`got ${dims}-d vector; lovorld's schema expects 1024-d`);
  }
  return `${model} → 1024-d OK`;
}

async function checkAuth() {
  const secret = requireEnv("AUTH_SECRET");
  if (secret.length < 32) {
    throw new Error(`AUTH_SECRET is too short (${secret.length} chars); use 32+ random bytes`);
  }
  const hasGithub = !!process.env.AUTH_GITHUB_ID && !!process.env.AUTH_GITHUB_SECRET;
  const hasGoogle = !!process.env.AUTH_GOOGLE_ID && !!process.env.AUTH_GOOGLE_SECRET;
  if (!hasGithub && !hasGoogle) {
    throw new Error(
      "no OAuth provider configured; set AUTH_GITHUB_ID/SECRET or AUTH_GOOGLE_ID/SECRET",
    );
  }
  const providers = [hasGithub ? "GitHub" : null, hasGoogle ? "Google" : null].filter(Boolean);
  return `secret OK, providers: ${providers.join(", ")}`;
}

async function main() {
  if (process.env.LOVORLD_DEMO_MODE === "1") {
    console.log(
      "\n\x1b[33m⚠ LOVORLD_DEMO_MODE=1 is set.\x1b[0m Real services will be bypassed at runtime.",
    );
    console.log("  Set LOVORLD_DEMO_MODE=0 in .env.local to use real credentials.\n");
  }

  console.log("Connectivity check:");
  await runCheck("Auth.js config", checkAuth);
  await runCheck("Postgres + pgvector", checkPostgres);
  const storageLabel =
    process.env.LOVORLD_LOCAL_STORAGE === "1"
      ? "Storage (local FS)"
      : process.env.BLOB_READ_WRITE_TOKEN
        ? "Storage (Vercel Blob)"
        : "Storage (Cloudflare R2)";
  await runCheck(storageLabel, checkStorage);
  await runCheck("Vision provider (image)", checkVision);
  await runCheck("Embedding provider (1024d)", checkEmbedding);

  const failed = results.filter((r) => r.status === "fail");
  const skipped = results.filter((r) => r.status === "skip");
  console.log();
  if (failed.length === 0 && skipped.length === 0) {
    console.log("\x1b[32m✓ All checks passed. Ready to go.\x1b[0m");
  } else {
    if (skipped.length > 0) {
      console.log(`\x1b[33m${skipped.length} skipped (likely not configured yet)\x1b[0m`);
    }
    if (failed.length > 0) {
      console.log(`\x1b[31m${failed.length} failed — fix the .env.local entries above.\x1b[0m`);
      process.exit(1);
    }
  }
}

main().catch((err) => {
  console.error("Check script crashed:", err);
  process.exit(1);
});
